CREATE TABLE IF NOT EXISTS "instructors" (
	"id" INTEGER NOT NULL DEFAULT 'nextval(''instructors_id_seq''::regclass)',
	"name" TEXT NULL DEFAULT NULL,
	"avatar_url" TEXT NULL DEFAULT NULL,
	"gender" TEXT NULL DEFAULT NULL,
	"services" TEXT NULL DEFAULT NULL,
	"birth" TIMESTAMP NULL DEFAULT NULL,
	"created_at" TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "members" (
	"id" INTEGER NOT NULL DEFAULT 'nextval(''members_id_seq''::regclass)',
	"name" TEXT NULL DEFAULT NULL,
	"avatar_url" TEXT NULL DEFAULT NULL,
	"email" TEXT NULL DEFAULT NULL,
	"gender" TEXT NULL DEFAULT NULL,
	"birth" TIMESTAMP NULL DEFAULT NULL,
	"blood" TEXT NULL DEFAULT NULL,
	"weight" INTEGER NULL DEFAULT NULL,
	"height" INTEGER NULL DEFAULT NULL,
	"instructors_id" INTEGER NULL DEFAULT NULL,
	PRIMARY KEY ("id")
);
